# Generated by Django 5.1.3 on 2025-07-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='ai_review_feedback',
            field=models.TextField(blank=True, help_text="AI's automated textual review/feedback on the user's message.", null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='ai_review_raw_response',
            field=models.JSONField(blank=True, help_text='Raw JSON response from the AI reviewer model (for debugging).', null=True),
        ),
    ]
