# Generated by Django 5.1.3 on 2025-07-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_messages_ai_review_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipatienttask',
            name='student_goals',
            field=models.TextField(blank=True, help_text='JSON list of specific objectives for the student to fulfill for this task (for internal evaluation).', null=True),
        ),
    ]
