# Generated by Django 5.1.3 on 2025-07-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0003_alter_aipatienttask_student_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipatientprofile',
            name='description',
            field=models.TextField(default=1, help_text="A brief overview or summary of the AI patient's background/situation."),
            preserve_default=False,
        ),
    ]
