# Generated by Django 5.1.3 on 2025-07-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0004_aipatientprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpermission',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was opened for this group.', null=True),
        ),
    ]
